server:
  port: 8081

mvc:
  pathmatch:
    matching-strategy: ant_path_matcher


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include:
      - aws

mybatis:
#  type-aliases-package: com.kosa.resq
  mapper-locations:  classpath:mapper/*/*.xml

cloud:
  aws:
    s3:
      bucket: heejinawsbucket1
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      instance-profile: true
