server:
  port: 8081

mvc:
  pathmatch:
    matching-strategy: ant_path_matcher


spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@ownit_high?TNS_ADMIN=./src/main/resources/OracleCloud/Wallet_OwnIt
    username: admin
    password: Ownit1234567

mybatis:
  type-aliases-package: com.kosa.ownit
  mapper-locations:  classpath:mapper/**/*.xml

